// patient
export const ADD_PATIENT_TO_STORE = "PATIENT.ADD_PATIENT_TO_STORE";
export const GET_PATIENTS = "PATIENT.GET_PATIENTS";
export const GET_PATIENTS_FULFILLED = "PATIENT.GET_PATIENTS_FULFILLED";

// doctor
export const ADD_DOCTOR_TO_STORE = "DOCTOR.ADD_DOCTOR_TO_STORE";
export const GET_DOCTORS = "DOCTOR.GET_DOCTORS";
export const GET_DOCTORS_FULFILLED = "DOCTOR.GET_DOCTORS_FULFILLED";

// admin
export const ADD_ADMIN_TO_STORE = "ADMIN.ADD_ADMIN_TO_STORE";

// record
export const ADD_RECORD_TO_STORE = "RECORD.ADD_RECORD_TO_STORE";
export const GET_RECORDS = "RECORD.GET_RECORDS";
export const GET_RECORDS_FULFILLED = "RECORD.GET_RECORDS_FULFILLED";
